name: 'Terraform backend'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/backend/**'
  workflow_dispatch:
    inputs:
      apply:
        description: 'Set to "true" to apply infrastructure changes'
        required: false
        default: 'false'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.YC_TOKEN }}
      CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      SSH_PUBLIC: ${{ secrets.SSH_PUBLIC }}
      SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.14.3"

    - name: Terraform Init
      run: terraform -chdir=./terraform/backend init

    - name: Terraform Format and Validate
      run: terraform -chdir=./terraform/backend validate

    - name: Terraform Plan
      run: |
        terraform -chdir=./terraform/backend plan -input=false -out=tfplan \
        -var="token=${{ secrets.YC_TOKEN }}" \
        -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
        -var="folder_id=${{ secrets.YC_FOLDER_ID }}" \
        -var="ssh_public=${{ secrets.SSH_PUBLIC }}"

    - name: Terraform Apply (Manual Trigger)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
      run: terraform -chdir=./terraform/backend apply -input=false tfplan